# Placeholder codebook – replace with project-specific content or export from INITIAL_CODEBOOK
version: "1.0"
created_date: "{{auto}}"
theoretical_framework: "Technology Acceptance Model + Diffusion of Innovation Theory"
codes: [] 